name: Deploy to EC2
on:
  push:
    branches:
      - main
jobs:
 name: Print environment variables
  run: |
    echo "SSH_PRIVATE_KEY: ${{ secrets.KEY }}"
    echo "REMOTE_HOST:  ${{ secrets.IP }}"
    echo "REMOTE_USER:  ${{ secrets.USER }}"
    echo "TARGET: ${{ secrets.TARGET_DIR }}"
  deploy:
    runs-on: ubuntu-latest
    steps:    
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Transfer files to EC2
        uses: easingthemes/ssh-deploy@v2.2.4
        env:
          SOURCE: "./"
          SSH_PRIVATE_KEY: ${{ secrets.KEY }}
          REMOTE_HOST: ${{ secrets.IP }}
          REMOTE_USER: ${{ secrets.USER }}
          TARGET: ${{ secrets.TARGET_DIR }}
        with:
          args: ssh -o StrictHostKeyChecking=no
