name: Deploy to EC2
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run start
      - name: Transfer files to EC2
        uses: tripoli80/scp-action@main
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: ./
          target: /home/ubuntu/crm-for-services
      - name: Connect to EC2
        uses: tripoli80/ssh-action@main
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/crm-for-services
            npm install --production
            pm2 restart all
