name: Deploy to EC2
on:
  push:
    branches:
      - main
jobs:
   deploy:
    runs-on: ubuntu-latest
    steps:    
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Run command on remote server
        uses: D3rHase/ssh-command-action@v0.2.2.4
        with:
          host: ${{secrets.IP}}
          user: ${{secrets.USER}}
          private_key: ${{secrets.KEY}}
          command: |
            cd ${{ secrets.TARGET_DIR }};
            sudo git checkout main;
            sudo git pull;
            sudo systemctl daemon-reload

