name: Deploy to Ubuntu server
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.KEY }}
          ssh-key-passphrase: ${{ secrets.KEY_PASSPHRASE }}

      - name: Run commands on remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          script: |
            cd ${{ secrets.TARGET_DIR }};
            sudo git checkout main;
            sudo git pull;
            sudo systemctl daemon-reload
