name: Deploy to EC2
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.0
      with:
        ssh-private-key: ${{ secrets.KEY }}
      - name: Run command on remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.IP}}
          user: ${{secrets.USER}}
          private_key: ${{secrets.KEY}}
          command: |
            cd ${{ secrets.TARGET_DIR }};
            sudo git checkout main;
            sudo git pull;
            sudo systemctl daemon-reload
