name: Deploy to Ubuntu server
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run commands on remote server
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.KEY }} ubuntu@${{ secrets.IP }} 'cd ${{ secrets.TARGET_DIR }} && git checkout main && git pull && systemctl daemon-reload'
