name: Deploy to Ubuntu server
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.KEY }}

      - name: Run commands on remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          script: |
            cd ${{ secrets.TARGET_DIR }};
            sudo git checkout main;
            sudo git fetch origin main;
            sudo git reset --hard origin/main
            sudo chmod -R 777 .;
            npm install;
            sudo systemctl restart ${{ secrets.NAME_SERVICES }}
