name: Deploy to Ubuntu server
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Group of log lines
        run: |
            echo "::group::My title"
            echo " ${{ secrets.KEY }}}"
            echo "::endgroup::"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: appleboy/ssh-scp-action@master
        with:
          ssh-private-key: ${{ secrets.KEY }}
          ssh-known-hosts: ${{ secrets.KNOWN_HOSTS }}
          host: ${{ secrets.IP }}
          username: ubuntu

      - name: Run commands on remote server
        uses: appleboy/ssh-scp-action@master
        with:
          ssh-private-key: ${{ secrets.KEY }}}
          host: ${{ secrets.IP }}
          username: ubuntu
          script: |
            cd ${{ secrets.TARGET_DIR }}
            git checkout main
            git pull
            systemctl daemon-reload
