name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:

    steps:
      - uses: actions/checkout@v2

      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./*
          remote_path: ${{ secrets.TARGET_DIR }}
          remote_host: ${{ secrets.IP }}
          remote_user: ubuntu
          remote_key: "${{ secrets.KEY }}"