name: Deploy to Ubuntu server
on:
  push:
    branches:
      - main

jobs:
  bash-example:
    runs-on: ubuntu-latest
    steps:
      - name: Group of log lines
        run: |
            echo "::group::My title2"
            echo "${{ secrets.KEY }}">privet.key
            cat privet.key
            ssh -o StrictHostKeyChecking=no -i privet.key ubuntu@3.66.84.144 'date'
            echo "::endgroup::"
